Modifications in CI workflow file.
Signed-off-by: Sophia Garg <sofigarg@amazon.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,15 +29,32 @@ jobs:
     - name: Build the stack
       run: docker-compose up -d         
       shell: bash
-      working-directory: ./test  
+      working-directory: ./test     
 
-    - name: Setting up OpenSearch domain 
-      run: python ./.github/workflows/test_url.py
-    
+    - name: Waiting for OpenSearch domain to be up.
+      run: |
+        counter=1
+        for counter in {1..10}
+        do
+          if [ $(curl -s -o /dev/null --head -w "%{http_code}" 'https://admin:admin@localhost:9200' -H 'Content-Type:application/json' --insecure -v) -ne 200 ]; then
+            sleep 30s
+          else
+            echo  "Waiting for addtional 30 seconds.. for Opensearch domain to be up."
+            sleep 30s
+            break 
+          fi  
+        done
+        if [ $counter -eq 11 ]; then
+          echo "Unable to connect with OpenSearch URL https://localhost:9200/"
+          exit 1
+        fi   
+      shell: bash
+      working-directory: ./test       
+   
     - name: Run script file
       run: |
           export NODE_TLS_REJECT_UNAUTHORIZED=0
           python driver-code.py 
       shell: bash
       working-directory: ./test
-     
+
